variable "environment" {}
variable "owner" {}
variable "cluster_name" {}
variable "vpc_name" {}
variable "region" {}
variable "cidr" {}
variable "public_subnets_cidr" {}
variable "private_subnets_cidr" {}
variable "workers_name_deployment" {}
variable "instance_type" {}
variable "keyname" {}